spring.application.name=sb-ecom
spring.output.ansi.enabled=always

# Database Configuration

# Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JWT Authentication Configuration
spring.app.jwtSecret=${JWT_SECRET}
spring.app.jwtExpirationMs=30000000
spring.ecom.app.jwtCookieName=SpringBootEcom

# JPA/Hibernate Configuration

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Custom Application Properties

project.images=images/
# Set maximum file size for a single uploaded file
spring.servlet.multipart.max-file-size=10MB

# Set maximum total request size for a multipart/form-data request
spring.servlet.multipart.max-request-size=10MB

# Server Configuration

server.port=${PORT:8080}

# Logging (Uncomment for debugging)

logging.level.org.springframework=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.com.ecommerce.sbecom=DEBUG